// The six ATHX 2027 program CSVs are generated by
// `scripts/build-athx-2027-programs.py` and imported through the admin
// program importer, so they have to satisfy the same parser the importer uses.
// This reads each file exactly as the importer does and checks the shape of
// what comes back, so a regenerated file that no longer imports cleanly fails
// here rather than at upload time.

import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { csvToProgram } from '../program-csv';
import { workoutToDays } from '../garmin/program-adapter';
import { mapWorkoutDay } from '../garmin/workout-mapper';
import type { Workout } from '@/models/types';

const DIR = path.join(process.cwd(), 'src/data/athx-2027');
const FILES = fs.readdirSync(DIR).filter(f => f.endsWith('.csv'));

describe('ATHX 2027 program CSVs', () => {
  it('ships one file per edition and division', () => {
    expect(FILES).toHaveLength(6);
  });

  it.each(FILES)('%s imports as a 84-day hybrid program', (file) => {
    const { id, data } = csvToProgram(fs.readFileSync(path.join(DIR, file), 'utf-8'));

    expect(id).toBeUndefined();               // no id column — imports as a new program
    expect(data.programType).toBe('hybrid');
    expect(data.name).toMatch(/^ATHX 2027 — (Men|Women)'s (Lite|ATHX|Pro) Division$/);
    expect(data.description.length).toBeGreaterThan(100);

    const days = data.workouts.map(w => w.day);
    expect(Math.min(...days)).toBe(1);
    expect(Math.max(...days)).toBe(84);
    expect(new Set(days).size).toBe(84);      // every day of the plan is present
    expect(days).toEqual([...days].sort((a, b) => a - b));

    for (const workout of data.workouts) {
      expect(workout.title.trim()).not.toBe('');
      for (const exercise of (workout as Workout).exercises) {
        expect(exercise.name.trim()).not.toBe('');
        expect(exercise.details.trim()).not.toBe('');
        expect(exercise.sessionType).toMatch(/^(strength|cardio)$/);
        expect(exercise.garminSport).toMatch(/^(RUNNING|CARDIO_TRAINING|STRENGTH_TRAINING|GENERIC)$/);
      }
    }
  });

  it.each(FILES)('%s keeps the double days as two sessions', (file) => {
    const { data } = csvToProgram(fs.readFileSync(path.join(DIR, file), 'utf-8'));

    const perDay = new Map<number, string[]>();
    for (const w of data.workouts) {
      perDay.set(w.day, [...(perDay.get(w.day) ?? []), w.title]);
    }
    const doubles = [...perDay.values()].filter(titles => titles.length === 2);
    expect(doubles).toHaveLength(23);
    for (const titles of doubles) {
      expect(titles[0]).toMatch(/^AM — /);
      expect(titles[1]).toMatch(/^PM — /);
    }

    // The twelve rest days carry the plan's rest-day guidance but schedule no work.
    const restDays = [...perDay.entries()].filter(([, t]) => t[0].toLowerCase().includes('rest'));
    expect(restDays.map(([day]) => day)).toEqual([4, 11, 18, 25, 32, 39, 46, 53, 60, 67, 74, 81, 83]);
  });

  it.each(FILES)('%s maps to Garmin workouts without scheduling rest days', (file) => {
    const { data } = csvToProgram(fs.readFileSync(path.join(DIR, file), 'utf-8'));

    // Competition day is a written brief, like the rest days — no session to sync.
    const guidanceOnly = (title: string) =>
      title.toLowerCase().includes('rest') || title === 'Competition';

    let mapped = 0;
    for (const workout of data.workouts) {
      const workouts = workoutToDays(workout as Workout).map(mapWorkoutDay).filter(Boolean);
      if (guidanceOnly(workout.title)) {
        expect(workouts).toHaveLength(0);
      } else {
        // Every training session has work in it, so every one reaches the watch.
        expect(workouts.length, `day ${workout.day} ${workout.title}`).toBeGreaterThan(0);
        mapped += workouts.length;
      }
    }
    expect(mapped).toBeGreaterThan(90);
  });
});
